apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: microservice-database
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: microservice-database
    spec:
      containers:
        - image: rsobook/microservice-database:1.0.1
          name: microservice-database
          ports:
          - containerPort: 5432
            protocol: TCP