apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ms-database
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-database
    spec:
      containers:
        - image: rsobook/ms-database:2.0.0
          name: ms-database
          ports:
          - containerPort: 5432
            protocol: TCP